const Employees=[
    {
        id:1,
        name:"Naveen",
        email:"bnaveen@tavisca.com",
        edit:true
    },
    {
        id:2,
        name:"Swar",
        email:"swar@tavisca.com",
        edit:true
    },
    {
        id:3,
        name:"Vamsi",
        email:"vamsi@tavisca.com",
        edit:true
    }
];
module.exports=Employees;
